### PR TITLE
Fixed setup.py install command

### PR DESCRIPTION
**Pull request by satyajitghana**

### CODE REVIEW

**Comment by rsy6318** [comment]
Hi, I think the setup.py install command is right and it can be installed successfully.

**Comment by satyajitghana** [comment]
```
❯ python3 setup.py --install
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --install not recognized
```

**Comment by satyajitghana** [comment]
`--install` is not a valid option, did you mean `install --user` ?

**Comment by rsy6318** [comment]
You can run 'python setup.py install' to install the pointnet2-lib, and the original cmd is right.

**Comment by satyajitghana** [comment]
In the readme it's written as `--install`

**Comment by rsy6318** [comment]
thanks, I will fix it.

**Pull request closed without merging**
